name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/app

            echo "Pull latest code"
            git pull origin main

            echo "Backend setup"
            cd backend
            npm install

            echo "Frontend build"
            cd ../frontend
            npm install
            npm run build

            echo "Restart backend"
            pm2 restart all

            echo "Reload nginx"
            systemctl reload nginx